packaging_format = 2

id = "yeswiki"
name = "YesWiki"
description.en = "Wiki that is quick and easy to use"
description.fr = "Wiki facile et rapide à prendre en main"

version = "4.4.1~ynh1"

maintainers = ["Florian Schmitt", "Nils Van Zuijlen", "Plumf"]

[upstream]
license = "AGPL-3.0-only"
website = "https://yeswiki.net/"
demo = "https://ferme.yeswiki.net/?CreerSonWiki"
admindoc = "https://yeswiki.net/?DocumentatioN"
code = "https://github.com/YesWiki/yeswiki"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/yeswiki"

    [install.init_main_permission]
    help.en = "If YesWiki is made public anyone will be able to view the wiki"
    help.fr = "Si YesWiki est rendu publique toute personne pourra consulter le wiki"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en", "ca", "es", "nl", "pt"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.wiki_name]
    ask.en = "Choose the wiki name"
    ask.fr = "Choisissez le nom de votre wiki"
    help.en = "If you want a name with spaces: replace them with %20 for each space."
    help.fr = "Si vous souhaitez un nom avec des espacements : remplacez les par %20 pour chaque espace"
    type = "string"
    default = "MyYunoHostWiki"

[resources]
        [resources.sources.main]
        url = "https://github.com/YesWiki/yeswiki/archive/refs/tags/v4.4.1.tar.gz"
        sha256 = "1f1a42b8596e4061b7f36c7956afcf097e90e8ea4963226cded587248f78e44f"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php7.4-zip, php7.4-curl, php7.4-gd, php7.4-dom, php7.4-mysql"

    [resources.database]
    type = "mysql"
